-- Script cập nhật số lượng cung cấp cho phù hợp với thực tế kinh doanh nội thất
-- Mặt hàng nội thất thường nhập số lượng nhỏ (5-30 sản phẩm/lần)

-- Cập nhật số lượng cung cấp theo từng nhà cung cấp
UPDATE CUNGCAP SET SOLUONGSP = 15 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Gỗ Việt%');
UPDATE CUNGCAP SET SOLUONGSP = 12 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%An Phát%');
UPDATE CUNGCAP SET SOLUONGSP = 8 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Minh Long%');
UPDATE CUNGCAP SET SOLUONGSP = 10 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Hoàng Gia%');
UPDATE CUNGCAP SET SOLUONGSP = 20 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Mây Tre%');
UPDATE CUNGCAP SET SOLUONGSP = 6 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Bát Tràng%');
UPDATE CUNGCAP SET SOLUONGSP = 5 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Anh Kim%');
UPDATE CUNGCAP SET SOLUONGSP = 18 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Hoàng Long%');
UPDATE CUNGCAP SET SOLUONGSP = 25 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Trang Trí Việt%');
UPDATE CUNGCAP SET SOLUONGSP = 30 WHERE MANCC IN (SELECT MANCC FROM NHA_CUNG_CAP WHERE TENNCC LIKE N'%Phúc An%');

-- Kiểm tra kết quả
SELECT 
    ncc.TENNCC AS N'Nhà cung cấp',
    sp.TENSP AS N'Sản phẩm',
    cc.SOLUONGSP AS N'Số lượng cung cấp'
FROM CUNGCAP cc
JOIN NHA_CUNG_CAP ncc ON cc.MANCC = ncc.MANCC
JOIN SAN_PHAM sp ON cc.MASP = sp.MASP
ORDER BY ncc.TENNCC;
